[package]
name = "cairo-wasm-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cairo-vm = { git = "https://github.com/lambdaclass/cairo-vm", default-features = false, features = "console_error_panic_hook" }
wasm-bindgen = "0.2"

[profile.release]
opt-level = "s" # Optimize for size
