[project]
name = "cairo-wasm-demo"
version = "0.1.0"
description = "Run & Prove Cairo code locally in the browser"
readme = "README.md"
requires-python = "==3.10.*"
dependencies = ["keth"]

[tool.uv.sources]
keth = { git = "https://github.com/kkrt-labs/keth", rev = "a109eae" }
